### ISSUE TITLE
报错 index out of range

### ISSUE THREAD

**Issue by hantmac** [jachinlin/kindle_maker#3]
```
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kindle_maker/ebook_maker.py", line 103, in parse_headers
    headers_info[-1]['next_headers'].append({

```
os: mac os
python version: python 3.6
how to use: make_ebook("source", "dist")

**Comment by jachinlin** [comment]
提供下 tocfile

**Comment by hantmac** [comment]
toc.md长这个样子，
![](https://ws4.sinaimg.cn/large/006tKfTcly1g1hhl071v0j317s0u0kjn.jpg)

**Comment by jachinlin** [comment]
代码出bug了。

你照着example里边来吧。toc.md第一行是标题（电子书名），不用`#`

**Comment by hantmac** [comment]
我之前就是按照example里面来的：
![](https://ws4.sinaimg.cn/large/006tKfTcly1g1i9wcwqpxj318y0u07b3.jpg)
我把`#`去掉后，还是报同样的错误。
ps:我看你代码里也有对第一行标题`#`处理的操作

**Comment by wajika** [comment]
> 代码出bug了。
> 
> 你照着example里边来吧。toc.md第一行是标题（电子书名），不用`#`

我这里也报了这错

(venv3) [root@loaclhost ~]# make_mobi /opt/html/ /opt/
Traceback (most recent call last):
  File "/root/venv3/bin/make_mobi", line 10, in <module>
    sys.exit(make_mobi_command())
  File "/root/venv3/lib/python3.6/site-packages/kindle_maker/__init__.py", line 16, in make_mobi_command
    make_mobi(args[0], args[1])
  File "/root/venv3/lib/python3.6/site-packages/kindle_maker/ebook_maker.py", line 126, in make_ebook
    title, headers = parse_headers(toc_file_name)
  File "/root/venv3/lib/python3.6/site-packages/kindle_maker/ebook_maker.py", line 99, in parse_headers
    headers_info[-1]['next_headers'].append({
IndexError: list index out of range


toc.md格式是
```

## 开篇词讲玩转编辑器，向高效能编程再进一步
## 01讲学编辑器，到底应该学什么
## 02讲VSCode的Why、How和What
## 03讲如何快速上手VSCode
## 05讲快捷键进阶攻略
## 06讲拒绝重复，你一定要学会的多光标特性
## 07讲如何快速在文件、符号、代码之间跳转(1)
## 08讲玩转鼠标操作
```

**Comment by wajika** [comment]
写上第一行 不加#，也是会报错

Error(kindlegen):E30005: Could not find file  Code.opf
cp: cannot stat ‘/opt/32fee8cf-6a2d-4a04-92a8-2acc4493492b/玩转VS’: No such file or directory
cp: cannot stat ‘Code.mobi’: No such file or directory
success


```
玩转vs
## 开篇词讲玩转编辑器，向高效能编程再进一步
## 01讲学编辑器，到底应该学什么
## 02讲VSCode的Why、How和What
## 03讲如何快速上手VSCode
## 05讲快捷键进阶攻略
## 06讲拒绝重复，你一定要学会的多光标特性
## 07讲如何快速在文件、符号、代码之间跳转(1)
## 08讲玩转鼠标操作
```

**Comment by jachinlin** [comment]
@wajika 试下

```
玩转vs
# 开篇词讲玩转编辑器，向高效能编程再进一步
# 01讲学编辑器，到底应该学什么
# 02讲VSCode的Why、How和What
# 03讲如何快速上手VSCode
# 05讲快捷键进阶攻略
# 06讲拒绝重复，你一定要学会的多光标特性
# 07讲如何快速在文件、符号、代码之间跳转(1)
# 08讲玩转鼠标操作
```

**Comment by wajika** [comment]
> @wajika 试下
> 
> ```
> 玩转vs
> # 开篇词讲玩转编辑器，向高效能编程再进一步
> # 01讲学编辑器，到底应该学什么
> # 02讲VSCode的Why、How和What
> # 03讲如何快速上手VSCode
> # 05讲快捷键进阶攻略
> # 06讲拒绝重复，你一定要学会的多光标特性
> # 07讲如何快速在文件、符号、代码之间跳转(1)
> # 08讲玩转鼠标操作
> ```

依然报错
```
Info:I9018:option: -donotaddsource: Source files will not be added
Info(prcgen):I1047: Added metadata dc:Title        "玩转VS"
Info(prcgen):I1047: Added metadata dc:Creator      "jachinlin.github.io"
Info(prcgen):I1002: Parsing files  0000039
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_372689_bwwwtosxtzp.eot
Info(cssparser):I10006: Invalid syntax for url(), ignoring the URI. "/opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html"
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_372689_bwwwtosxtzp.svg#iconfont
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_372689_bwwwtosxtzp.ttf
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_372689_bwwwtosxtzp.woff
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_372689_bwwwtosxtzp.eot#iefix
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_509397_1cyjv4o90qiod2t9.eot
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_509397_1cyjv4o90qiod2t9.svg#player-font
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_509397_1cyjv4o90qiod2t9.ttf
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_509397_1cyjv4o90qiod2t9.woff
Warning(prcfile):W14028: Following file does not exist :   //at.alicdn.com/t/font_509397_1cyjv4o90qiod2t9.eot#iefix
Info(cssparser):I10004: @rules other than @import, @charset and @font-face are not supported.
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/resource/image/46/84/4664e7f29ac02da1d451f23986ff9f84.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/resource/image/3d/4d/3db377b4d31768f5885efa4d79ecf04d.png
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/resource/image/92/06/92862660523add24b3168f22954fa506.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/60/a9/66d90640.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/af/6f/90c51bc0.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/59/0e/09e2cf5d.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c6/62/3f1be4ff.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/4e/f9/b12388bd.jpg
Warning(prcgen):W14009: media file not specified  
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/9e/30/732ec6ce.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/f1/31/5001390b.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c8/7c/2aa545db.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/ca/6a/10d837b1.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/ec/87/3ff8d8d1.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/a8/a9/31aa3e98.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c5/0c/6f07ebda.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/57/4f/6fb51ff1.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/68/f0/7f05411b.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/d1/91/86beceaf.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/7c/c8/da4f5c8f.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/4a/c7/7c44a260.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/88/2c/87861bb1.jpg
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: relative' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: absolute' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-width' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'overflow-x' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28004: Absolute value specified for CSS property in content is not supported by Kindle readers. Please use % or refer Kindle Publishing Guidelines about usage of property: 'line-height' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: fixed' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-height' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'overflow' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/开篇词讲玩转编辑器，向高效能编程再进一步.html
Info(cssparser):I10006: Invalid syntax for url(), ignoring the URI. "/opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html"
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/resource/image/bf/cb/bff6d7c199712d992035a76d0f84aecb.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/9d/93/945393c1.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/b7/f6/4e1e20db.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/49/2c/b920ea41.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/df/6e/267bd6ee.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c6/ab/30f26137.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/a5/f7/0263a8e2.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/b4/9a/17309b19.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/2c/a2/def0bf4d.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/4f/ba/6cefa19a.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/bf/d8/09d678a6.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/ca/b7/5c451afd.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/b3/a8/f74d604a.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/12/0f/4d38a315.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/cf/5f/8b69cda3.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c5/85/2651f4dd.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/12/c7/68/04b3b8a6.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/11/f9/ad/3fa5756f.jpg
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: relative' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: absolute' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-width' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'overflow-x' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28004: Absolute value specified for CSS property in content is not supported by Kindle readers. Please use % or refer Kindle Publishing Guidelines about usage of property: 'line-height' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28003: Value specified for CSS property in content is not supported by Kindle readers. Please refer Kindle Publishing Guidelines about usage of property: 'position: fixed' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-height' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'overflow' in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/01讲学编辑器，到底应该学什么.html
Error(core):E1005: Could not access file.
      in file: /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/24讲前端语言支持：JavaScript和Node.html
Info(cssparser):I10006: Invalid syntax for url(), ignoring the URI. "/opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/02讲VSCode的Why、How和What.html"
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/resource/image/b0/9d/b0f1f587ba8154ed928482456e62af9d.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/24/42/99e346c7.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/1e/a1/dc9388da.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/ae/e0/3e636955.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/de/13/c355d4be.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/10/08/d4/abb7bfe3.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/5a/e8/b46e1901.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/49/ef/39147375.jpg
Warning(prcgen):W14010: media file not found  /opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/https:/static001.geekbang.org/account/avatar/00/0f/56/ea/a88d4a46.jpg
Warning(prcgen):W14010: media file not found  http://thirdwx.qlogo.cn/mmopen/vi_32/ajNVdqHZLLA7LRG63vamnAAPaibCxGyT3yepLmobloOfMDPGibd5Rtcvq7pzE9NgCFXo8gZXYx1p44BcPlEr4ung/132
cp: cannot stat ‘/opt/9e43202a-a46f-42d1-9c83-638ccc4f9d3b/玩转VS.mobi’: No such file or directory
success
```

**Comment by wajika** [comment]
> @wajika 试下
> 
> ```
> 玩转vs
> # 开篇词讲玩转编辑器，向高效能编程再进一步
> # 01讲学编辑器，到底应该学什么
> # 02讲VSCode的Why、How和What
> # 03讲如何快速上手VSCode
> # 05讲快捷键进阶攻略
> # 06讲拒绝重复，你一定要学会的多光标特性
> # 07讲如何快速在文件、符号、代码之间跳转(1)
> # 08讲玩转鼠标操作
> ```

没人回复了

**Comment by cr7kaka10** [comment]
楼主还在么？遇到同样问题了

**Comment by jachinlin** [comment]
@cr7mufc520 @wajika @hantmac 使用最新的代码试试 有问题的话把 toc.md 文件和错误信息贴出来，thx
