### ISSUE TITLE
geektime_dl 也是这个错误，kindle_maker 也是，Exec format error

### ISSUE THREAD

**Issue by HackettYu** [jachinlin/kindle_maker#7]
## 版本

- Python 3.6.7
- Ubuntu

## 报错
```bash
Traceback (most recent call last):
  File "/usr/local/bin/make_mobi", line 10, in <module>
    sys.exit(make_mobi_command())
  File "/usr/local/lib/python3.6/dist-packages/kindle_maker/__init__.py", line 17, in make_mobi_command
    make_mobi(args[0], args[1])
  File "/usr/local/lib/python3.6/dist-packages/kindle_maker/ebook_maker.py", line 165, in make_ebook
    subprocess.call([kindlegen, '-dont_append_source', opf_file])
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.6/dist-packages/kindle_maker/bin/linux/kindlegen'
```

**Comment by grg909** [comment]
我也是这个报错！

**Comment by HackettYu** [comment]
反正最后我没管它，因为我发现在里面有个文件能用 calibre 转成 pdf

**Comment by grg909** [comment]
刚刚我解决了，发现是kindlegen的支持问题，我系统缺了个库，sudo apt-get install qemu-user-static 就好了

**Comment by Triple-Z** [comment]
在 Windows WSL 下，一模一样的错 +1。
